# This is a multi channel image message including rgb, depth, gray, ir, multi_spectral with a timestamp.
#
Header header

sensor_msgs/Image nav_left
sensor_msgs/Image obs_left
sensor_msgs/Image ir
sensor_msgs/Image multi_spectral0
sensor_msgs/Image multi_spectral1
sensor_msgs/Image multi_spectral2
sensor_msgs/Image multi_spectral3
sensor_msgs/Image multi_spectral4
sensor_msgs/Image multi_spectral5
sensor_msgs/Image multi_spectral6
sensor_msgs/Image multi_spectral7
sensor_msgs/Image multi_spectral8
sensor_msgs/Image depth
sensor_msgs/PointCloud2 point_cloud
sensor_msgs/Imu imu
geometry_msgs/Pose CarCurPQ
